name: 3 Tier Workspace CI CD MERN Stack

on: workflow_dispatch
env:
  fimg: "frontend_image"
  bimg: "backend_image"
  fcont: "frontend_container"
  bcont: "backend_container"
  dbname: "mongodb"
  fport: 5173
  bport: 5050
  dbport: 27017
  mern_net: "mern-docker-network"

jobs:
  CI_CD_for_MERN:
    runs-on: self-hosted
    steps:

    - name: Install Docker if not present
      run: |
        if ! command -v docker &> /dev/null
        then
          echo "Docker not found. Installing..."
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
        else
          echo "Docker already installed"
        fi

    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: "Remove Already Running Containers"
      run: |
        sudo docker stop ${{env.fcont}} || true
        sudo docker rm   ${{env.fcont}} || true
        
        sudo docker stop ${{env.bcont}} || true
        sudo docker rm ${{env.bcont}} || true

        sudo docker stop ${{env.dbname}} || true
        sudo docker rm ${{env.dbname}} || true
     
    - name: "Pull MongoDB & Build Docker Images"
      run: |
        sudo docker pull mongo:6

        sudo docker build -t ${{env.fimg}} mern/frontend
        sudo docker build -t ${{env.bimg}} mern/backend

    - name: "Ensure Docker Network Exists"
      run: |
        if sudo docker network ls --format '{{.Name}}' | grep -wq "${{ env.mern_net }}"; then
          echo "Network ${{ env.mern_net }} already exists. Removing..."
          sudo docker network rm ${{ env.mern_net }}
        fi
        echo "Creating Docker network ${{ env.mern_net }}..."
        sudo docker network create ${{ env.mern_net }}
             
    - name: "Run Docker Images"
      run: |
        sudo docker run -d \
        --network=${{env.mern_net}} \
        --name=${{env.fcont}} \
        -p ${{env.fport}}:${{env.fport}}  \
        --restart=always \
        ${{env.fimg}}

        sudo docker run -d \
        --network=${{env.mern_net}} \
        --name=${{env.dbname}} \
        -p ${{env.dbport}}:${{env.dbport}} \
        --restart=always \
        mongo:6 
        sleep 5

        sudo docker run -d \
        --network=${{env.mern_net}} \
        --name=${{env.bcont}} \
        -p ${{env.bport}}:${{env.bport}} \
        --restart=always \
        ${{env.bimg}}

